name: Upload Output

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install ardrive
        run: npm install -g ardrive-cli

      - name: Upload output
        run: ardrive upload-file --local-path ./daily_output.json -F "4b4ffe84-a6de-48d0-9b85-c56db14084a5" -s ${{ secrets.SEEDPHRASE }} --no-bundle --upsert
